#!/bin/bash
#

set AUDIODEV=hw:1

DECODER=~/elec3607-labquestions/labs/lab5-audio/wsprcan/k9an-wsprd

TMPOUT='_wsprd.out'

pactl load_module module_loopback source=alsa_input.usb-Plugable_Plugable_USB_Audio_Device_000000000000-00.analog-stereo

cd ~/elec3607-labquestions/labs/lab3-i2c/
./si5351


decode () {
	date
	cd /elec3607-labquestions/labs/lab5-audio/
	paplay data/iq-16b.wav & ./wsprcan/k9an-wsprd
	#sleep 110
}

while true
do
	sec=$(date +'%S')
	min=$(date +'%M')
	# wait for an even minute
	if (("10#$min" % 2 == 0 && "10#$sec" == 0 )); then
		echo -n "Executing wspr_decode "
		decode
	elif ((10#$sec < 49)); then
		sleep 10
	fi
done
